---

- name: Install and Start  Nginx
  hosts: all
  become: root

  tasks: 
    - name: Install Nginx
      apt:
        name: nginx
        state: present
    - name: Start Nginx
      service: 
        name: nginx
        state: started
